[project]
name = "windsurf-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datastar-py>=0.6.3",
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "google-generativeai>=0.8.5",
    "werkzeug>=3.1.3",
]
